### ISSUE TITLE
Service user is deactivated

### ISSUE THREAD

**Issue by m-menon** [dreamfactorysoftware/df-core#10]
hi,

I accidentally ended up disabling the user service in DF 2.1. The [message](https://github.com/dreamfactorysoftware/df-core/blob/351a94daf96df612aff1c566f250bab1563256a6/src/Services/BaseRestService.php#L62) that is shown now is "Service user is deactivated". I have even tried updating mysql table service and set the field is_active to 1 but to no avail. Any help on this matter?

I am running Dreamfactory 2.1.1 on Centos 7

Thanks,
M.M

**Comment by leehicks** [comment]
You will need to clear the application's cache if you directly change the underlying database. Use 'php artisan cache:clear' in the root dreamfactory directory.

**Comment by m-menon** [comment]
cool thanks. Will do that. Btw was my method of setting the is_active field of table "service" the right thing to do to get the access back? I mean I was locked out of the system and had no choice but to try updating the mysql "service" table...thanks

**Comment by leehicks** [comment]
The admin app "should" have let you still log in as an admin using the system/admin/session path, but looks like there is a bug in the implementation, bails early on inactive service. I will get that cleared up. 
If clearing the cache works, close this issue and I will move this to the admin app repo, thanks.

**Comment by m-menon** [comment]
sure thanks a lot. I will try it out in about 10 mins and will close this once confirmed. Thanks once again for your time :+1:

**Comment by m-menon** [comment]
cool, it works. Really appreciate your help. Is there any place I can get a list of services that are critical to the working of DF so that I do not disable of meddle with those in the future?

Cheers,
M.M

**Comment by m-menon** [comment]
Thanks a lot
