### ISSUE TITLE
Python script always print event

### ISSUE THREAD

**Issue by minixalpha** [dreamfactorysoftware/df-core#12]
If I enable a Python script, dreamfactory always print event.

in `\DreamFactory\Core\Scripting\Engines\Python::enrobeScript`

```php
try:
    def my_closure(event, platform):
python;
        foreach ($scriptLines as $sl) {
            $enrobedScript .= "\n        " . $sl;
        }

        $enrobedScript .= <<<python

    event['script_result'] =  my_closure(event, platform);
except Exception as e:
    event['script_result'] = {'error':str(e)};
    event['exception'] = str(e)

print event;
```

Is it a bug or feature? user can print event themselves.

**Comment by df-arif** [comment]
This is not a bug. This is how Python script output is sent over to PHP side. Is this causing any issues?

**Comment by minixalpha** [comment]
I add a python script to log the user email

```python
email = platform['session']['user']['email']
print(email)
```
but in the log, the script output not only contains user's email, but also contains the event,

like 

```
foo@bar.com
{'resource': '', 'script_result': None, ...
```
the '{'resource': '', 'script_result': None, ...' is the content of the `event`.

So, how can I make the output of script only contains user's email?

I think the `\DreamFactory\Core\Scripting\Engines\Python::enrobeScript` should be 

```php
try:
    def my_closure(event, platform):
python;
        foreach ($scriptLines as $sl) {
            $enrobedScript .= "\n        " . $sl;
        }

        $enrobedScript .= <<<python

    event['script_result'] =  my_closure(event, platform);
except Exception as e:
    event['script_result'] = {'error':str(e)};
    event['exception'] = str(e)

    print event;
```

so `print event` only be executed when Exception. After I change the code, script output only print 
user's email.

**Comment by df-arif** [comment]
If you use your suggested change and only print event during Exception then doing `return email` from your script won't work. 

That being said, we have recently made some changes in the scripting area that will no longer log the entire event but only things that you print from script. Feel free to checkout the code in develop branch `src/Handlers/Events/ServiceEventHandler.php` line:201 and `src/Scripting/Services/Script.php` line:110. Follow the call to `$engine->runScript` method above those lines for more details.

**Comment by minixalpha** [comment]
ok, thanks for your reply. @df-arif
