### ISSUE TITLE
HAS_ONE relationship does not work with composite primary keys

### ISSUE THREAD

**Issue by tvarsis** [dreamfactorysoftware/df-core#33]
Updated from 2.5.x to latest version and a lot of our relationships have gone from HAS MANY to HAS ONE, which is wrong and breaking the code. I'm guessing this is due to that we have composite primary keys on the junction tables which then breaks with the new implementation of HAS ONE that looks on primary key, but does not seem to realize that they are actually composite primary keys, and not a single column primary key. We use Postgres and we have a bunch of tables that have junction tables that have composite primary keys in the form of:

client_id
user_id

**Comment by leehicks** [comment]
Could you give me an example table set up with the relationships, or a _schema/<table_name> dump  from 2.5 and 2.8 showing the relationships?

**Comment by tvarsis** [comment]
You can use the below Postgres query to create a template for testing. In 2.5 it will result in HAS MANY relationship, and in latest DF version it will be HAS ONE.

CREATE TABLE "public"."client" (
  "id" serial4 NOT NULL,
  "name" varchar,
  CONSTRAINT "client_pkey" PRIMARY KEY ("id"));

CREATE TABLE "public"."user" (
  "id" serial4 NOT NULL,
  "name" varchar,
  CONSTRAINT "user_pkey" PRIMARY KEY ("id"));

CREATE TABLE "public"."x_client_user" (
  "client_id" int4 NOT NULL,
  "user_id" int4 NOT NULL,
  "date_added" timestamp(6) NOT NULL DEFAULT date_trunc('second'::text, now()),
  "date_removed" timestamp(6),
  "date_updated" timestamp(6),
  "used_count" int8 DEFAULT 0,
  CONSTRAINT "x_client_user_pkey" PRIMARY KEY ("client_id", "user_id"),
  CONSTRAINT "x_client_user_client" FOREIGN KEY ("client_id") REFERENCES "public"."client" ("id") ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT "x_client_user_user" FOREIGN KEY ("user_id") REFERENCES "public"."user" ("id") ON DELETE CASCADE ON UPDATE NO ACTION );

CREATE INDEX "x_client_user_client_id_index" ON "public"."x_client_user" USING btree (
  "client_id" "pg_catalog"."int4_ops" ASC NULLS LAST );

CREATE INDEX "x_client_user_user_id_index" ON "public"."x_client_user" USING btree (
  "user_id" "pg_catalog"."int4_ops" ASC NULLS LAST );

**Comment by leehicks** [comment]
Sorry for the delayed response, I put a fix in for this before the holiday [here](https://github.com/dreamfactorysoftware/df-database/commit/ce3201f946dbf5e1cef5c9855c74c5407461ce88). You can use `composer update dreamfactory/df-database` to pull it in the latest install. If this doesn't fix the issue for you, please let me know.
