### ISSUE TITLE
Private Lookup Key value is always **********

### ISSUE THREAD

**Issue by meiti** [dreamfactorysoftware/df-core#4]
I'm using private lookup keys in SQL Server connection string, but during database connection the following error occurs:

{"error":{"context":null,"message":"Failed to connect to database.\nConnection failed to open the DB
 connection: SQLSTATE[HY000] Unknown host machine name (severity 2)"
...

I have checked the source code and I think BaseSystemLookup class always returns ********** for private keys!!!

**Comment by df-arif** [comment]
It's fixed [here](https://github.com/dreamfactorysoftware/df-core/commit/56def335149ffa7c93a811d6c9ff0d3836135ef7)
